# Generated by Django 3.0.6 on 2020-10-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
