# Generated by Django 3.0.6 on 2020-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201013_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='addition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='deduction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
